import React from "react";


export default function Table(props) {
    const {tr,th}=props;
    return ( 
        <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>{th}</th>
                    <th>{th}</th>
                    <th>{th}</th>
                    <th>{th}</th>
                    <th>{th}</th>
                    <th>{th}</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    {tr}
                </tr>
            </tfoot>
            <tbody>
                <tr>{tr}
                    
                </tr>
                <tr>
                    {tr}
                </tr>
                <tr>
                    {tr}
                </tr>
                <tr>
                    {tr}
                </tr>
                <tr>
                    {tr}
                </tr>
                <tr>
                    {tr}
                </tr>
                <tr>
                   {tr}
                </tr>
                <tr>
                    {tr}
                </tr>
                <tr>
                    {tr}
                </tr>
                <tr>
                    {tr}
                </tr>
                <tr>
                    {tr}
                </tr>
                <tr>
                     {tr}
                </tr>
                <tr>
                    {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
                <tr>
                {tr}
                </tr>
            </tbody>
        </table>
    </div>
    )
}